---
layout: news
title: Weld 2.3.0.Final released!
author: Martin Kouba
priority: 1
change_frequency: weekly
---

Weld 2.3.0.Final has been just released! From now on, 2.3 is the current stable version of Weld and 2.2 is not actively developed anymore - i.e. no new features are added, only bugs will be fixed. Weld 2.3 will remain a *CDI 1.2* implementation. We are incrementing the minor version due to several new features added. Weld 2.3 is also included in link:http://wildfly.org/[WildFly 10] application server.

Notable features and changes:

* Java 6 support was dropped - Java 7 is the minimal requirement for building and running Weld 2.3
* Weld 2.3 comes with a special mode for application development, the link:http://docs.jboss.org/weld/reference/2.3.0.Final/en-US/html/devmode.html#probe[Probe development tool] allows to inspect application CDI components at runtime
* Weld SE Bootstrap API was enhanced in many ways - new features are mostly backported from link:http://weld.cdi-spec.org/news/2015/08/05/weld-300Alpha12/#_weld_se_bootstrap_api[Weld 3 development branch]
* Weld Servlet now supports Undertow web server
* Revised delivery of `@Initialized`/`@Destroyed` events for `@ApplicationScoped` in an EAR (see also link:https://issues.jboss.org/browse/WELD-1821[WELD-1821])

&#91; link:http://docs.jboss.org/cdi/api/1.2/[CDI 1.2 API] &#93;
&#91; link:http://weld.cdi-spec.org/download/[Download] &#93;
&#91; link:http://docs.jboss.org/weld/reference/2.3.0.Final/en-US/html/[Documentation] &#93;
&#91; link:https://issues.jboss.org/projects/WELD/versions/12328057[Release notes] &#93;

== Weld 2.2.16.SP1

In addition, Weld 2.2.16.SP1 has been also released. It's a bugfix release for 2.2 branch.

&#91; link:https://issues.jboss.org/projects/WELD/versions/12327594[Weld 2.2.16.Final Release notes] &#93;
&#91; link:https://issues.jboss.org/projects/WELD/versions/12328216[Weld 2.2.16.SP1 Release notes] &#93;
