---
layout: news
title: Weld 2.4.0.Final
author: Martin Kouba
priority: 1
change_frequency: weekly
excerpt: The first stable version of the 2.4 branch (CDI 1.2) arrived.
desc: Weld 2.4.0.Final released
tags: [release]
---
:linkattrs:

I am very pleased to announce the *first stable version of Weld 2.4* (CDI 1.2).
See also https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12331363[the release details, window="_blank"].
From now on, 2.4 is the current stable version of Weld and 2.3 is not actively developed anymore.
Thanks to everyone involved in this release!

Most of the new features were already introduced in link:/news/2016/08/19/weld-240CR1[First release candidate of Weld 2.4, window="_blank"].
To sum it up:

* Removed dependency on `com.google.guava:guava`
* Enhanced version of `javax.enterprise.inject.Instance`
* Veto `AnnotatedType` not annotated with a bean defining annotation
* `@ActivateRequestScope` interceptor binding moved to Weld API and renamed to `@ActivateRequestContext`
* Improved rolling upgrades support
* Events - reflect the output of CDI-494
* Probe - allow to filter unused beans
* Cleanup, cleanup, cleanup...
* Initial Java 9 support

Moreover, 2.4.0.Final allows to export the Probe development tool data (to be discussed in one of the following blog posts) and fixes a minor problem in non-EE environments (see also link:https://issues.jboss.org/browse/WELD-2227[WELD-2227]).

In the coming weeks, the Weld team is also going to publish *"Weld tips"* - a series of concise articles.
The intention is to familiarize developers with less known Weld features.
There will be no hot news, just useful existing features (repetition is the mother of wisdom ;-).


== WildFly Patch

As usual, a link:http://download.jboss.org/weld/2.4.0.Final/wildfly-10.1.0.Final-weld-2.4.0.Final-patch.zip[patch for WildFly, window="_blank"] is available. This time the target platform is *WildFly 10.1.0.Final*.  If you’re not familiar with patching WildFly, check link:http://blog.eisele.net/2015/02/playing-with-weld-probe-see-all-of-your.html[Markus's tutorial, window="_blank"].

&#91; link:http://docs.jboss.org/cdi/api/1.2/[CDI 1.2 API, window="_blank"] &#93;
&#91; link:/download/[Download] &#93;
&#91; link:http://docs.jboss.org/weld/reference/2.4.0.Final/en-US/html/[Documentation, window="_blank"] &#93;
&#91; link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12331363[Release notes, window="_blank"] &#93;