---
layout: news
title: Weld 3.0.0.CR1
author: Martin Kouba
priority: 1
change_frequency: weekly
excerpt: Weld 3.0.0.CR1 (CDI 2.0-PFD) released. And it's almost Final!
desc: Weld 3.0.0.CR1 released
tags: [release]
---
:linkattrs:

I am very pleased to announce the release of Weld *3.0.0.CR1* (aligned with *CDI 2.0-PFD*).
See also https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12331714[the release details, window="_blank"].
Thanks to everyone involved in this release!
This version of Weld will be part of the JSR 365 Approval Ballot (watch http://cdi-spec.org/[CDI spec website, window="_blank"] for news).
The Beta1 version of Weld 3 turned out to be sufficiently stable and so the first release candidate is mostly dedicated to cleanup and minor optimizations.
We would like to release Weld *3.0.0.Final* (stable version of CDI 2.0) in early February.

== WildFly Patch

As usual, a link:http://download.jboss.org/weld/3.0.0.CR1/wildfly-10.1.0.Final-weld-3.0.0.CR1-patch.zip[patch for WildFly, window="_blank"] is available. 
This time the target platform is *WildFly 10.1.0.Final*.  
If you’re not familiar with patching WildFly, check the link:/documentation/#12[FAQ].

&#91; link:/download/[Download] &#93;
&#91; link:http://docs.jboss.org/weld/reference/3.0.0.CR1/en-US/html/[Documentation, window="_blank"] &#93;
&#91; link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12331714[Release notes, window="_blank"] &#93;