---
layout: news
title: Weld 2.4.2.Final
author: Martin Kouba
priority: 1
change_frequency: weekly
excerpt: Another bugfix version of Weld 2.4 (CDI 1.2) is here. Today with some CDI 2 stuff!
desc: Weld 2.4.2.Final released
tags: [release]
---
:linkattrs:

As you may know, CDI 2 (JSR 365) is in Public Review phase.
That's great news for early adopters.
But for now, I am very pleased to announce another production-ready version of *Weld 2.4* (CDI 1.2).
See also https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12332808[the release details, window="_blank"].
Thanks to everyone involved in this release!

WARNING: There is a link:https://issues.jboss.org/browse/WELD-2328[regression, window="_blank"] in Weld *2.4.2.Final*. The problem only occurs if a link:https://docs.oracle.com/javase/tutorial/essential/environment/security.html[Security Manager, window="_blank"] is used. However, users are encouraged to upgrade to *2.4.2.SP1* which contains a fix for the issue.

Notable fixes and improvements:

* Added *trimmed bean archives* support (CDI 2.0, link:https://issues.jboss.org/browse/WELD-2314[WELD-2314, window="_blank"])
* Fixed Weld SE and Weld Servlet cooperation (link:https://issues.jboss.org/browse/WELD-2260[WELD-2260, window="_blank"] and link:https://issues.jboss.org/browse/WELD-2262[WELD-2262, window="_blank"])
* Fixed `ActivateRequestContextInterceptor` - align the priority with CDI 2.0, fire `@Initialized` and `@Destroyed` events (CDI 2.0, link:https://issues.jboss.org/browse/WELD-2281[WELD-2281, window="_blank"])
* Fixed JDK9 build problems (link:https://issues.jboss.org/browse/WELD-2303[WELD-2303, window="_blank"] and link:https://issues.jboss.org/browse/WELD-2301[WELD-2301, window="_blank"])
* Validation - allow to use CDI 2 rules when validating selected alternatives in `bean.xml` (link:https://issues.jboss.org/browse/WELD-2313[WELD-2313, window="_blank"])
* Performance improvements in `javax.enterprise.inject.Instance` implementation (CDI 2.0, link:https://issues.jboss.org/browse/WELD-2323[WELD-2323, window="_blank"])
* Illegal bean types ignored for a session bean (link:https://issues.jboss.org/browse/WELD-2315[WELD-2315, window="_blank"])
* Dependency upgrade - `jboss-classfilewriter` to 1.2.1.Final (enables interception of default methods, see also link:https://issues.jboss.org/browse/WELD-2093[WELD-2093, window="_blank"])
* Weld SE - addded useful methods from `SeContainerInitializer` (CDI 2.0, link:https://issues.jboss.org/browse/WELD-2316[WELD-2316, window="_blank"])
* Probe development tool - extended bean archive info

== WildFly Patch

As usual, a link:http://download.jboss.org/weld/2.4.2.Final/wildfly-10.1.0.Final-weld-2.4.2.Final-patch.zip[patch for WildFly, window="_blank"] is available.
This time the target platform is *WildFly 10.1.0.Final*.
If you’re not familiar with patching WildFly, check the link:/documentation/#12[FAQ].

&#91; link:http://docs.jboss.org/cdi/api/1.2/[CDI 1.2 API, window="_blank"] &#93;
&#91; link:/download/[Download] &#93;
&#91; link:http://docs.jboss.org/weld/reference/2.4.0.Final/en-US/html/[Documentation, window="_blank"] &#93;
&#91; link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12332808[Release notes, window="_blank"] &#93;