---
layout: news
title: Weld 4.0.0.Beta1
author: Matej Novotny
priority: 1
change_frequency: weekly
excerpt: Weld 4.0.0.Beta1 released
desc: Weld 4.0.0.Beta1 released
tags: [release]
---
:linkattrs:

A new Weld 4 release is now available!
Latest core version is now 4.0.0.Beta1 and Weld API that ships with it is 4.0.Beta1.

I will not be listing links to issues as usual, because I think more important work was done outside of JIRA tracking this time (although you can check the issues link:https://issues.redhat.com/projects/WELD/versions/12346364[here]).
Instead, let me sum it up in a short list of noticeable changes:

* All Weld bits are now present in Maven Central
** Including servlet core (and shaded) which had to be left out last time
* We are able to execute CDI TCKs in EE 9 environment once again and it's all passing
* We are now able to test servlets with Tomcats and Undertow
** Jetty testing is not possible yet because there is no link:https://github.com/arquillian/arquillian-container-jetty/issues/43[Arquillian adapter] for it yet
* Reworked documentation generation tooling
** Weld docs now have similar look to those of CDI and are distributed in either PDF or single page HTML format
* Did some updates on Javadoc generation in API and Core if generated with JDK 11
* Big update pass on tooling and dependencies
** We are now using Dependabot and have bumped almost every dependency and tooling in the project
** Which also led to nice cleanup and fixing of several issues

On top of that, every bugfix that would go into Weld 3 is of course being added to Weld 4 as well so those aren't missing either!

== WildFly Patch

Sadly we cannot provide a patch for WildFly as there is not yet any official release that would support EE 9.
As soon as there is one, we will surely follow up with Weld patch!


&#91; link:/download/[Download] &#93;
&#91; link:http://docs.jboss.org/weld/reference/4.0.0.Beta1/en-US/html_single/[Documentation, window="_blank"] &#93;
&#91; link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310891&version=12346364[Release notes, window="_blank"] &#93;
